services:
  - type: web
    name: document-verification-ocr
    env: python
    region: singapore
    rootDir: ocr-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    aptPackages:
      - tesseract-ocr
      - poppler-utils
